name: PHP Unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v1
    - uses: 26/phpunit@master
      with:
        config: tests/phpunit/phpunit.xml
        memory: 256M
